site_name: ThemeFinder documentation
site_url: https://i-dot-ai.github.io/themefinder/
repo_url: https://github.com/i-dot-ai/themefinder

nav:
  - Home: index.md
  - API Reference: api_reference.md
  - Examples:
    - Kaggle Tweet Analysis: example_nb.ipynb
  - Contributing:
    - Documentation: contributing_to_docs.md
  - Evaluation: evaluation.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.follow
    - search.suggest

plugins:
  - search
  - mkdocs-jupyter:
      include_source: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            heading_level: 1
            show_symbol_type_heading: false
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
            docstring_section_style: table
            merge_init_into_class: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - attr_list
